### ISSUE TITLE
flickering on open and resizing to desktop height

### ISSUE THREAD

**Issue by davidosomething** [timeyyy/pytknvim#7]
OSX 10.10.5
desktop resolution 2560x1600 (NON-retina mode, no scaling)
two monitors, pytknvim opens on primary (listed above)

video demo: http://screencast.com/t/2rwCaQeHiGa

Tcl 8.5 & Tk 8.5 (8.5.9)

trying to resize to a smaller sizes causes redraws like this too, until the window fills the desktop height

**Comment by timeyyy** [comment]
hi david, thanks for the feedback, i have no mac but will put a plan of attack up soon
